#!/usr/bin/env node

var daemon = require("daemonize2").setup({
    main: "server.js",
    name: "identifid",
    pidfile: "identifid.pid"
});

switch (process.argv[2]) {
    case undefined:
    case "start":
        daemon.start();
        break;

    case "stop":
        daemon.stop();
        break;

    default:
        console.log("Usage: [start|stop]");
}