#!/usr/bin/env node

var fs = require('fs');
var datadir = process.env.IDENTIFI_DATADIR || (require('os').homedir() + '/.identifi');

if (!fs.existsSync(datadir)) {
  fs.mkdirSync(datadir);
}

var daemon = require("daemonize2").setup({
    main: require.resolve('identifi-daemon'),
    name: "identifid",
    pidfile: datadir + "/identifid.pid",
    cwd: '.'
});

switch (process.argv[2]) {
    case undefined:
    case "start":
        daemon.start();
        break;

    case "stop":
        daemon.stop();
        break;

    default:
        console.log("Usage: [start|stop]");
}
