#!/usr/bin/env node

var fs = require('fs');
var osHomedir = require('os-homedir');
var datadir = process.env.IDENTIFI_DATADIR || (osHomedir() + '/.identifi');

if (!fs.existsSync(datadir)) {
  fs.mkdirSync(datadir);
}

var daemon = require("daemonize2").setup({
    main: require.resolve('identifi-daemon'),
    name: "identifid",
    pidfile: datadir + "/identifid.pid",
    cwd: '.'
});

switch (process.argv[2]) {
    case undefined:
    case "start":
        daemon.start();
        try {
          require.resolve('identifi-angular');
          console.log('Identifi web app: http://127.0.0.1:4944/');
        } catch (e) {
          console.log('Identifi API: http://127.0.0.1:4944/api');
        }
        break;

    case "stop":
        daemon.stop();
        break;

    default:
        console.log("Usage: [start|stop]");
}
